build-beneficiary:
	docker build -f beneficiary-service/Dockerfile -t beneficiary-service:1.0 .
build-notification:
	docker build -f notification-service/Dockerfile -t notification-service:1.0 .
build-gateway:
	docker build -f gateway-service/Dockerfile -t gateway-service:1.0 .
