GET http://localhost:8080/questions
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:8080/questions
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "title": "How to use PostgreSQL with Spring Boot and JPA",
  "description": "I want to use PostgreSQL with Spring Boot and JPA and develop RESTful APIs."
}

###