/**
 * Beneficiary Profiles API
 * A restful API to manage corporate beneficiary profiles
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface IdTypeRequest {
    /**
     * Name of ID used for corporate(registration certificate, ministry of industry certificate) or individual(passport or license)
     */
    name?: string;
    /**
     * ID number for the ID type mentioned in the name
     */
    number?: string;
    /**
     * Attach ID document here
     */
    document?: string;
    /**
     * Expiry date of the ID card presented
     */
    expiryDate?: string;
}
