GET http://localhost:8080/beneficiary
Accept: application/json

###

POST http://localhost:8080/beneficiary
Content-Type: application/json

{
  "fullName": "qasim",
  "nationality": "jordanian"
}

###

PUT http://localhost:8080/beneficiary/5e78fe127e4c464a986b463f
Content-Type: application/json

{
  "fullName": "qasim ali",
  "nationality": "jordanian"
}

###

DELETE http://localhost:8080/beneficiary/5e78fe127e4c464a986b463f
Content-Type: application/json

###

DELETE http://localhost:8080/beneficiary
Content-Type: application/json

###
